import requests
import json
from langchain_core.tools import tool
from dotenv import load_dotenv
import os

load_dotenv()
kie_api_key = os.getenv("KIE_API_KEY")

# API 配置常量
API_BASE_URL = "https://api.kie.ai/api/v1"
CREATE_TASK_URL = f"{API_BASE_URL}/jobs/createTask"
RECORD_INFO_URL = f"{API_BASE_URL}/jobs/recordInfo"
CALLBACK_URL = None

# 图像生成默认配置
DEFAULT_IMAGE_SIZE = "square_hd"
DEFAULT_IMAGE_RESOLUTION = "1K"
DEFAULT_MAX_IMAGES = 1

# 视频生成默认配置
DEFAULT_ASPECT_RATIO = "landscape"
DEFAULT_N_FRAMES = "10"


def _get_headers(content_type="application/json"):
    """获取请求头"""
    headers = {"Authorization": f"Bearer {kie_api_key}"}
    if content_type:
        headers["Content-Type"] = content_type
    return headers

@tool
def text_to_image_by_seedream_v4_model_create_task(prompt: str):
    """Create a task to generate an image from a prompt by seedream-v4 model. Returns the task ID."""

    payload = {
        "model": "bytedance/seedream-v4-text-to-image",
        "callBackUrl": CALLBACK_URL,
        "input": {
            "prompt": prompt,
            "image_size": DEFAULT_IMAGE_SIZE,
            "image_resolution": DEFAULT_IMAGE_RESOLUTION,
            "max_images": DEFAULT_MAX_IMAGES
        }
    }

    response = requests.post(CREATE_TASK_URL, headers=_get_headers(), data=json.dumps(payload))
    result = response.json()

    return result["data"]["taskId"]


@tool
def image_to_image_by_seedream_v4_edit_model_create_task(prompt: str, image_url: str):
    """Create a task to edit an image from a prompt by seedream-v4 edit model. Returns the task ID. Image URL is the URL of the image to edit."""

    payload = {
        "model": "bytedance/seedream-v4-edit",
        "callBackUrl": CALLBACK_URL,
        "input": {
            "prompt": prompt,
            "image_urls": [image_url],
            "image_size": DEFAULT_IMAGE_SIZE,
            "image_resolution": DEFAULT_IMAGE_RESOLUTION,
            "max_images": DEFAULT_MAX_IMAGES
        }
    }

    response = requests.post(CREATE_TASK_URL, headers=_get_headers(), data=json.dumps(payload))
    result = response.json()
    # {
    # "code": 200,
    # "message": "success",
    # "data": {
    #     "taskId": "task_12345678"
    # }
    # }
    return result["data"]["taskId"]


@tool
def get_task_status(task_id: str):
    """
    Returns the status of the all KIE AI tasks or the URL of the image generated by the task. Task ID is the ID of the task to get the result of. 
    If the task is not successful, returns error code and error message.
    If the task is successful, returns the URL of the image.
    """

    params = {"taskId": task_id}
    response = requests.get(RECORD_INFO_URL, headers=_get_headers(content_type=None), params=params)
    result = response.json()

    if result["data"]["status"] == "success":
        return result["data"]["resultJson"]["resultUrls"][0]
    else:
        return {result["data"]["failCode"]: result["data"]["failMsg"]}


@tool
def text_to_video_by_sora2_model_create_task(prompt: str):
    """Create a task to generate a video from a prompt. Returns the task ID. Prompt is the prompt to generate the video from."""

    payload = {
        "model": "sora-2-text-to-video",
        "callBackUrl": CALLBACK_URL,
        "input": {
            "prompt": prompt,
            "aspect_ratio": DEFAULT_ASPECT_RATIO,
            "n_frames": DEFAULT_N_FRAMES,
            "remove_watermark": True
        }
    }

    response = requests.post(CREATE_TASK_URL, headers=_get_headers(), data=json.dumps(payload))
    result = response.json()

    return result["data"]["taskId"]

@tool
def  first_frame_to_video_by_sora2_model_create_task(prompt: str, image_url: str):
    """Create a task to generate a video from a first frame. Returns the task ID. Image URL is the URL of the image to generate the video from."""

    payload = {
        "model": "sora-2-image-to-video",
        "callBackUrl": CALLBACK_URL,
        "input": {
                    "prompt": prompt,
                    "image_urls": [ 
                        image_url
                    ],
                    "aspect_ratio": DEFAULT_ASPECT_RATIO,
                    "n_frames": DEFAULT_N_FRAMES,
                    "remove_watermark": True
        }
    }
    
    response = requests.post(CREATE_TASK_URL, headers=_get_headers(), data=json.dumps(payload))
    result = response.json()

    return result["data"]["taskId"]