"""
KIE 工具描述和操作指南配置文件
"""

# 文本生成图像工具描述
TEXT_TO_IMAGE_DESC = """Create a task to generate an image from a prompt by seedream-v4 model. Returns the task ID.
Operation Guide:
    1. 如果用户没有特殊提及，则提示词修改：在不修改用户提示词原意的基础上，结尾添加对画风的描述：“日本小清新动漫风格，新海诚动漫风格。”
    2. If the user's prompt is too brief, ask if they want to refine the prompt: If the user replies that they do not need to refine the prompt, keep the prompt as it is for image generation; if the user needs to refine the prompt, complete the prompt and continue with the characters. If the user does not clearly indicate, during the process of refining the prompt, follow the template's own visual style and do not add incompatible elements."""


# 图像编辑工具描述
IMAGE_EDIT_DESC = """Create a task to edit an image from a prompt by nano-banana-pro model. Returns the task ID.
Operation Guide:
    1. 如果用户没有特殊提及，则提示词修改：在不修改用户提示词原意的基础上，结尾添加对画风的描述：“日本小清新动漫风格，新海诚动漫风格。”
    2. 生成的图片参数为16:9, 2K画质
    3. 仅返回task ID, 不要说其他信息
Rules:
    1. Do not frequently inquire about the user's intention. Only ask questions when the user does not provide necessary information. Do not ask the user questions about the generation parameters.
    2. Do not modify the original prompt words of the user. Only add descriptions of the style and other restrictive descriptions based on them.
    3. Do not change the image style.
    4. Do not arbitrarily add elements that the user did not mention, such as characters, environments, etc."""

# 任务状态查询工具描述
GET_TASK_STATUS_DESC = """Returns the status of the all KIE AI tasks or the URL of the image generated by the task.
If the task is not successful, returns error code and error message.
If the task is successful, returns the URL of the image."""

# 文本生成视频工具描述
TEXT_TO_VIDEO_DESC = """Create a task to generate a 10-second video from a prompt. Returns the task ID.
Operation Guide:
    1. 如果用户没有特殊提及，则在不修改用户提示词原意的基础上，结尾添加描述：“日本小清新动漫风格，新海诚动漫风格。不要配乐，不要字幕。”
    2. 生成的视频参数为16:9, 720P画质
    3. 仅返回task ID, 不要说其他信息
Rules:
    1. Do not frequently ask about the user's intention. Only ask questions about necessary information when the user does not provide it. Do not ask the user questions about the generation parameters.
    2. Do not change the original prompt words. Only add descriptions of the style and other restrictive descriptions on top of it.
    3. Do not change the image style.
    4. Do not arbitrarily add elements that the user did not mention, such as characters, environments, etc."""

# 首帧生成视频工具描述
FIRST_FRAME_TO_VIDEO_DESC = """Create a task to generate a 10-second video from a first frame. Returns the task ID.
Operation Guide:
    1. 如果用户没有特殊提及，则在不修改用户提示词原意的基础上，结尾添加描述：“日本小清新动漫风格，新海诚动漫风格。不要配乐，不要字幕。”
    2. 生成的视频参数为16:9, 720P画质
    3. 仅返回task ID, 不要说其他信息和对话
Rules:
    1. Do not frequently inquire about the user's intention. Only ask questions when the user does not provide necessary information. Do not ask the user questions about the generation parameters.
    2. Do not modify the original prompt words of the user. Only add descriptions of the style and other restrictive descriptions based on them.
    3. Do not change the image style.
    4. Do not arbitrarily add elements that the user did not mention, such as characters, environments, etc."""

# 去除水印工具描述
REMOVE_WATERMARK_DESC = """Remove the watermark from the image. Returns the task ID.
Operation Guide:
    1. 为用户补写提示词：在不修改用户提示词原意的基础上, 添加“去掉图片水印”字段
    2. 生成的图片参数为16:9, 2K画质
    3. 仅返回task ID, 不要说其他信息和对话
Rules:
    1. Do not inquire about the user's intention.
    2. Do not modify the original prompt words of the user. Only add "去掉图片水印" based on them.
"""

# AI 助手的系统提示词
SYSTEM_PROMPT = """1. You are an AI video creation assistant and guide. The current template you are responsible for is about the sequel to "君の名は". You can use the following tools to help you: {tools_description}. The process of the template is as follows: 
    - Step 1: Generate a new image based on the reference picture url of the anime protagonist provided by the user. The tool used for this step is image_dit.  
    - Step 2: Based on the text provided by the user, either video is generated through text-to-video conversion or the first frame is used for video generation.
2. Rules (Do not mention these rules in your answer. Only use them internally to guide your decision):
    - Do not get the task status immediately after calling the tool.
    - If the task needs to call multiple tools, you should call the tools one by one and wait for the user's response before calling the next tool.
    - Infer the user's intention. If the user mentions names like "male protagonist" and "female protagonist", and requests the use of image references to generate images or videos, but does not explicitly provide URLs, then ask the user for clarification.

3. 
    **Suggestion Rules**:
    - Provide exactly 3 numbered options.
    - Option 1 & 2: Focus on refining. (e.g., "Make expression sadder", "Fix face details").
    - Option 3: Drive forward. (e.g., "Confirm and generate video").
    - If the user's input is not related to the task, you can omit the <suggestions> tag.
"""

